import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        {
            type: "doc",
            id: "intro",
            label: "Getting Started",
        },
        {
            type: "category",
            label: "Odoo",
            collapsible: true,
            collapsed: true,
            link: {
                type: "doc",
                id: "odoo/overview",
            },
            items: [{ type: "autogenerated", dirName: "odoo" }],
        },
        {
            type: "category",
            label: "Odoo.SH",
            collapsible: true,
            collapsed: true,
            link: {
                type: "doc",
                id: "odoosh/overview",
            },
            items: [{ type: "autogenerated", dirName: "odoosh" }],
        },
        {
            type: "doc",
            id: "options",
            label: "Options",
        },
    ],
};

export default sidebars;
