name: Build and Release Extension

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION=${{ inputs.version }}
          else
            VERSION=${GITHUB_REF:11}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create a tag
        if: github.event_name == 'workflow_dispatch'
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: "v${{ steps.get_version.outputs.version }}"

  build:
    name: Build Extension
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4

      - name: Update extension version
        run: sed -i "s/{{EXTENSION_VERSION}}/${{ needs.prepare.outputs.version }}/" package.json

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Clean dist directory
        run: rm -rf dist/

      - name: Run build script
        run: |
          bun run zip
          bun run zip:firefox

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-builds
          path: |
            dist/odoo-toolbox-${{ needs.prepare.outputs.version }}-chrome.zip
            dist/odoo-toolbox-${{ needs.prepare.outputs.version }}-firefox.zip
            dist/odoo-toolbox-${{ needs.prepare.outputs.version }}-sources.zip

  upload-stores:
    name: Upload to Stores
    runs-on: ubuntu-latest
    needs: [prepare, build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-builds
          path: dist/

      - name: Upload to stores
        run: |
          bun wxt submit \
            --chrome-zip dist/odoo-toolbox-${{ needs.prepare.outputs.version }}-chrome.zip \
            --firefox-zip dist/odoo-toolbox-${{ needs.prepare.outputs.version }}-firefox.zip --firefox-sources-zip dist/odoo-toolbox-${{ needs.prepare.outputs.version }}-sources.zip
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          CHROME_PUBLISH_TARGET: default
          CHROME_SKIP_SUBMIT_REVIEW: false
          FIREFOX_EXTENSION_ID: odoo_toolbox@thcl-saju
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [prepare, build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-builds
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.prepare.outputs.version }}"
          name: "Release v${{ needs.prepare.outputs.version }}"
          generate_release_notes: true
          files: |
            dist/odoo-toolbox-${{ needs.prepare.outputs.version }}-chrome.zip
            dist/odoo-toolbox-${{ needs.prepare.outputs.version }}-firefox.zip
